content iteration
tus/tus.io pull request #176
Opened 2020-11-03 16:52 UTC by WardenScotland

2020-11-05 09:19 UTC, Acconut requested changes
Wow, thank you very, very much for these impressive changes! It's mostly looking good, expect for some formatting issues

2020-11-05 09:19 UTC, Acconut commented on _content/support.md
> +
Can you remove the empty new lines here?

2020-11-05 09:19 UTC, Acconut commented on _content/implementations.md
> +
In this file, there is a lot of whitespace added. Maybe your editor did that on its own but - if possible - please remove the whitespace again. We have a convention that if a line contains no text, it should also contain no whitespace :)

2020-11-05 09:19 UTC, Acconut commented on _content/faq.md
> -- At first, the client sends a `POST` request to the server to initiate the upload. This *upload creation request* tells the server basic information about the upload, such as its size or additional
In some cases, the backticks (`) were removed. We like to keep them as formatting instruction, so the words in the backticks render as code in the website. Could you undo these deletions? This occurred in multiple files, I think.

2020-11-05 10:15 UTC, WardenScotland commented
Thanks for the notes, Marius. I will address each comment today. I use Typora as my markdown editor and it looks like it messed up some of the file formattings.

2021-02-23 12:52 UTC, kvz commented
@WardenScotland can you please revisit this so it's ready for a layer of polish by @AJvanLoon?

2021-03-04 14:12 UTC, Acconut approved these changes

2021-03-04 14:13 UTC, Acconut commented
Took care of the changes on my own. Using some RegExp magic, it was quickly done and we can merge this to wipe out my bad spelling from the homepage :D

2021-03-04 14:13 UTC, merged