Fix SEO issues to impove the Ahrefs' Health Score
tus/tus.io pull request #425
Opened 2024-01-02 12:32 UTC by nqst

Made some changes that should improve our SEO [Health Score](https://help.ahrefs.com/en/articles/1424673-what-is-health-score-and-how-is-it-calculated-in-ahrefs-site-audit) provided by Ahrefs. As of Dec 2023, the score was 87%. 

**Changes:**

- Fixed broken links.
- Added `og:image` and other Open Graph & Twitter tags.
- Added meta descriptions for the most important pages. Haven't added descriptions to all blog posts, but added an example one to the most recent post.
- Fixed the [Noindex page in sitemap](https://help.ahrefs.com/en/articles/2754358-what-does-the-noindex-page-in-sitemap-issue-in-site-audit-mean) issue.
- Optimized a heavyweight image.

**Unrelated change:** running `yarn inject:protocol` added some changes to the protocol that weren't added before.

2024-01-02 12:45 UTC, nickrttn approved these changes
That's amazing @nqst 👏 

Is the example blog post description ok to go live with or should someone (@Acconut?) write descriptions for each post?

2024-01-02 12:54 UTC, nqst commented
> Is the example blog post description ok to go live? 

Yeah, that's just an excerpt from the blog post introduction, so it should be good to go.

> Should someone write descriptions for each post?

Ideally, yes, although that's a secondary priority compared to adding descriptions to the homepage and the pages that we have in the navbar.

2024-01-03 20:54 UTC, kvz approved these changes
💯💯💯💯
✨✨💖✨
💯💯💯💯

2024-01-08 15:21 UTC, Acconut requested changes
That's a great change, thank you very much, Alex!

2024-01-08 15:21 UTC, Acconut commented on scripts/inject-protocol.sh
> +description: "The Tus protocol specification: Detailing the interactions between Tus clients and servers for reliable and resumable file uploads."
We do use the capitalized `Tus` on transloadit.com, but on tus.io we prefer `tus` for now :)

2024-01-08 15:21 UTC, Acconut commented on src/content/protocols/0.1.x.md
> +  'The Tus protocol specification: Detailing the interactions between Tus
```suggestion
  'The tus protocol specification: Detailing the interactions between tus
```

2024-01-08 15:21 UTC, Acconut commented on src/content/protocols/0.2.x.md
> +  'The Tus protocol specification: Detailing the interactions between Tus
```suggestion
  'The tus protocol specification: Detailing the interactions between tus
```

2024-01-08 15:21 UTC, Acconut commented on src/content/protocols/1.0.x.md
> +  'The Tus protocol specification: Detailing the interactions between Tus
```suggestion
  'The tus protocol specification: Detailing the interactions between tus
```

2024-01-08 15:21 UTC, Acconut commented on scripts/inject-protocol.sh
> +description: "The Tus protocol specification: Detailing the interactions between Tus clients and servers for reliable and resumable file uploads."
```suggestion
description: "The tus protocol specification: Detailing the interactions between tus clients and servers for reliable and resumable file uploads."
```

2024-01-08 15:21 UTC, Acconut commented on src/pages/blog/index.astro
> +const description = 'Explore our Blog for the latest updates and insights on resumable file uploading technology and protocol developments.'
```suggestion
const description = 'Explore our blog for the latest updates and insights on resumable file uploading technology and protocol developments.'
```

2024-01-08 15:21 UTC, Acconut commented on src/pages/demo.mdx
> +  'Experience the Tus protocol in action with our live demo, showcasing
```suggestion
  'Experience the tus protocol in action with our live demo, showcasing
```

2024-01-08 15:21 UTC, Acconut commented on src/pages/faq.md
> +  'Find answers to your questions about Tus. Get insights on how Tus facilitates
```suggestion
  'Find answers to your questions about tus. Get insights on how tus facilitates
```

2024-01-08 15:21 UTC, Acconut commented on src/pages/implementations.astro
> +const description = 'Explore real-life Tus protocol implementations in various languages and platforms, showcasing its versatility and efficiency in file uploads.'
```suggestion
const description = 'Explore real-life tus protocol implementations in various languages and platforms, showcasing its versatility and efficiency in file uploads.'
```

2024-01-08 15:21 UTC, Acconut commented on src/pages/index.astro
> +const description = 'Tus is the open protocol standard for resumable and reliable file uploads across the web, facilitating efficient and seamless file transfer experiences.'
```suggestion
const description = 'tus is the open protocol standard for resumable and reliable file uploads across the web, facilitating efficient and seamless file transfer experiences.'
```

2024-01-08 15:21 UTC, Acconut commented on src/pages/support.mdx
> +  community for protocol guidance, or opt for advanced support for your Tus
```suggestion
  'Explore community and commercial support options for tus. Engage with our
  community for protocol guidance, or opt for advanced support for your tus
```

2024-01-08 15:22 UTC, Acconut approved these changes

2024-01-08 15:29 UTC, merged